// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9joiegWr_aswP_RlldMY5bU22aTuxdc',
    appId: '1:926415037859:android:a235311ef6294503072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    storageBucket: 'praise-to-god.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOuXKILnG20ugyJOqRHQgkqzW0BPIqLI',
    appId: '1:926415037859:ios:22712542afee6452072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    storageBucket: 'praise-to-god.firebasestorage.app',
    androidClientId: '926415037859-p109gv817623ishd16lrb6acksd94n2s.apps.googleusercontent.com',
    iosClientId: '926415037859-fkggp2i27o1br1k0o5qi1et7ga6jquf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.praiseToGod',
  );
}
