// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkT-C-Wmh1DHQF2lEYyOZf_Ktf9kenSFQ',
    appId: '1:1071232002847:android:bab10d0b0311ae16ca1e2a',
    messagingSenderId: '1071232002847',
    projectId: 'praisetogod-test',
    storageBucket: 'praisetogod-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqG0geZGqqFFf2Pt4KDW0ex9vLP1RPN8',
    appId: '1:1071232002847:ios:2dd7e4cbda4ca2d6ca1e2a',
    messagingSenderId: '1071232002847',
    projectId: 'praisetogod-test',
    storageBucket: 'praisetogod-test.firebasestorage.app',
    androidClientId: '1071232002847-0d15llfco74c1gm054bn4s74ajp1am7d.apps.googleusercontent.com',
    iosClientId: '1071232002847-7r4vj754k0p4fp1shsjvd95k87l8bp8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.praiseToGod',
  );
}
