// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEqSiXA4Lh-dkWIKN_YiHEQ58FWAczu4Q',
    appId: '1:926415037859:web:0c296c42187202bb072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    authDomain: 'praise-to-god.firebaseapp.com',
    storageBucket: 'praise-to-god.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9joiegWr_aswP_RlldMY5bU22aTuxdc',
    appId: '1:926415037859:android:4d72f03634911ad0072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    storageBucket: 'praise-to-god.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOuXKILnG20ugyJOqRHQgkqzW0BPIqLI',
    appId: '1:926415037859:ios:3b85a240c0ea9784072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    storageBucket: 'praise-to-god.firebasestorage.app',
    iosBundleId: 'com.example.praiseToGod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKOuXKILnG20ugyJOqRHQgkqzW0BPIqLI',
    appId: '1:926415037859:ios:3b85a240c0ea9784072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    storageBucket: 'praise-to-god.firebasestorage.app',
    iosBundleId: 'com.example.praiseToGod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEqSiXA4Lh-dkWIKN_YiHEQ58FWAczu4Q',
    appId: '1:926415037859:web:862bd88c954e9c8d072616',
    messagingSenderId: '926415037859',
    projectId: 'praise-to-god',
    authDomain: 'praise-to-god.firebaseapp.com',
    storageBucket: 'praise-to-god.firebasestorage.app',
  );
}
